c/shared/source/uforead/uforead.c: fix `message()` format argument (gcc-14)
Upcoming `gcc-14` enabled a few warnings into errors, like
`-Wint-conversion`. This caused `afdko` build to fail as:

    /build/afdko/c/shared/source/uforead/uforead.c:1243:20: error: passing argument 2 of ‘message’ makes pointer from integer without a cast [-Wint-conversion]
     1243 |         message(h, ufoErrParse, "Encountered glyph reference %s in alternate layer's contents.plist with an empty file path. ", glyphName);
          |                    ^~~~~~~~~~~
          |                    |
          |                    int

It looks like `ufoErrParse` is an unexpected parameter here.

While at it fixed build failure related to int/pointer error:

    /build/afdko/c/shared/source/uforead/uforead.c:2007:16: error: returning ‘void *’ from a function with return type ‘long int’ makes integer from pointer without a cast [-Wint-conversion]
     2007 |         return NULL;
          |                ^~~~