[buildcff2fv] update to new fontTools exceptions
- updated to catch (and generate) `fontTools.varLib.cff.VarLibCFFPointTypeMergeError` instead of old `MergeTypeError`
- removed redefinition of `MergeTypeError`