/build/afdko/c/shared/source/tx_shared/tx_shared.c: fix parameter type (gcc-14)
Upcoming `gcc-14` enabled a few warnings into errors, like
`-Wincompatible-pointer-types`. This caused `afdko` build to fail as:

    /build/afdko/c/shared/source/tx_shared/tx_shared.c: In function ‘stmInit’:
    /build/afdko/c/shared/source/tx_shared/tx_shared.c:526:20: error: assignment to ‘size_t (*)(ctlStreamCallbacks *, void *, char **)’ {aka ‘long unsigned int (*)(struct ctlStreamCallbacks_ *, void *, char **)’} from incompatible pointer type ‘size_t (*)(ctlStreamCallbacks *, Stream *, char **)’ {aka ‘long unsigned int (*)(struct ctlStreamCallbacks_ *, Stream *, char **)’} [-Wincompatible-pointer-types]
      526 |     h->cb.stm.read = stm_read;
          |                    ^

The change fixes opaque parameter to pass as `void *`.