[makeotf] No need to remove the existing font
Possible fix for https://ci.appveyor.com/project/adobe-type-tools/afdko/build/1.0.432
Traceback (most recent call last):
  File "c:\python27-x64\lib\site-packages\afdko\Tools\SharedData\FDKScripts\MakeOTF.py", line 3062, in main
    runMakeOTF(makeOTFParams)
  File "c:\python27-x64\lib\site-packages\afdko\Tools\SharedData\FDKScripts\MakeOTF.py", line 2736, in runMakeOTF
    os.remove(outputPath)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process